jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    default_context:
        serialization:
            enable_max_depth_checks: true
    metadata:
        auto_detection: true
        directories:
            v1:
                namespace_prefix: App\Api\V1
                path: "%kernel.project_dir%/config/serializer/v1"
                version: '1.0'
    handlers:
        datetime:
            default_format: Y-m-d H:i:s

when@prod:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
