name: PHPUnit Tests

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  behat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, opcache, pdo, pdo_mysql, zip
          coverage: none

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --no-suggest

      - name: Create metadata directory
        run: mkdir -p config/serializer/v1

      - name: Run phpunit tests
        run: ./vendor/bin/phpunit
