name: Run Tests

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: greatfoods_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, opcache, pdo, pdo_mysql, zip
          coverage: none

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --no-suggest

      - name: Set up environment variables
        env:
          APP_ENV: test
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "APP_ENV=${APP_ENV}" >> $GITHUB_ENV
          echo "APP_SECRET=${APP_SECRET}" >> $GITHUB_ENV
          echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV
          echo "APP_ENV=${APP_ENV}" > .env
          echo "APP_SECRET=${APP_SECRET}" >> .env
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "APP_ENV=${APP_ENV}" > .env.test
          echo "APP_SECRET=${APP_SECRET}" >> .env.test
          echo "DATABASE_URL=${DATABASE_URL}" >> .env.test

      - name: Create metadata directory
        run: mkdir -p config/serializer/v1

      - name: Run behat tests
        run: ./vendor/bin/behat

      - name: Run phpunit tests
        run: ./vendor/bin/phpunit
